# Install prerequisites
- name: check if pip is installed
  command: which pip
  register: pip_task_installed
  changed_when: no
  failed_when: no

- name: download pip installer
  get_url:
    url=https://bootstrap.pypa.io/get-pip.py
    dest="/tmp/get-pip.py"
  become: yes
  when: pip_task_installed is defined and
        pip_task_installed.rc is defined and
        pip_task_installed.rc != 0

- name: run installer
  command: "{{ ansible_python_interpreter | default('python') }} /tmp/get-pip.py"
  become: yes
  when: pip_task_installed is defined and
        pip_task_installed.rc is defined and
        pip_task_installed.rc != 0

- name: check installed version
  command: pip --version
  register: pip_task_version
  changed_when: no
  failed_when: no

- name: Install cryptography
  pip:
    name:
      - cryptography>=2.7
      - requests>=2.22
      - pyopenssl>=19.0.0


