- name: Generate Prefix/subnet variables for DMVPN Spoke route updates
  hosts: dmvpn-spoke-g004
  connection: network_cli
  gather_facts: False
  vars_files: Null 
  vars: Null 
  tasks:
    - name: Render prefix_list.yaml hostvars
      template:
        src: templates/dmvpn_spoke_prefixList_vars.j2
        dest: prefix_list.yaml

    - name: Pause 10 seconds
      pause:
        seconds: 10